# Generated by Django 2.0.6 on 2018-07-03 14:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fiim', 'Официальные документы ФИИМ'), ('protocol', 'Протоколы собраний'), ('sk', 'Судейский комитет'), ('dk', 'Дисциплинарный комитет')], max_length=100)),
                ('pdf', models.FileField(upload_to='')),
                ('created_at', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(default='вице-президент', max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(default='images/official-no-img.jpg', upload_to='images/')),
                ('started_at', models.DateField()),
                ('document', models.FileField(upload_to='')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='official',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiim.Region'),
        ),
        migrations.AddField(
            model_name='document',
            name='participant',
            field=models.ManyToManyField(related_name='documents', to='fiim.Official'),
        ),
    ]
