# Generated by Django 2.0.6 on 2018-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/partners')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('fiim', 'Нормативные документы'), ('protocol', 'Протоколы собраний'), ('order', 'Приказы'), ('sk', 'Судейский комитет'), ('dk', 'Дисциплинарный комитет')], max_length=100),
        ),
        migrations.AlterField(
            model_name='official',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='official',
            name='photo',
            field=models.ImageField(default='images/officials/official-no-img.jpg', upload_to='images/officials'),
        ),
    ]
