# Generated by Django 2.0.6 on 2018-07-15 16:15

from django.db import migrations, models
import django.db.models.deletion


def fill_document_type(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    DocumentType = apps.get_model("fiim", "DocumentType")
    db_alias = schema_editor.connection.alias
    DocumentType.objects.using(db_alias).bulk_create([
        DocumentType(name="Документы", code="fiim"),
        DocumentType(name="Протоколы собраний", code="protocol"),
        DocumentType(name="Судейский и дисциплинарный комитет", code="skdk"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('fiim', '0002_add_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('published', models.BooleanField()),
                ('icon', models.CharField(default='fa fa-file', max_length=50)),
            ],
        ),
        migrations.RunPython(fill_document_type),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fiim.DocumentType'),
        ),
    ]
