# Generated by Django 2.0.7 on 2018-07-20 15:43

from django.db import migrations, models
import django.db.models.deletion
import fiim.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiim', '0004_document_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf',
            field=models.FileField(upload_to=fiim.models.document_type_path),
        ),
        migrations.AlterField(
            model_name='official',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiim.Document'),
        ),
        migrations.AlterField(
            model_name='official',
            name='position',
            field=models.CharField(default='Вице-президент', max_length=300),
        ),
    ]
