# Generated by Django 2.1.2 on 2018-12-15 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiim', '0008_documenttype_sorting_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
